export interface GroceryItem {
  name: string;
  category: string;
  aliases?: string[]; // Alternative names/spellings
  common: boolean; // True for most common items
}

export const groceryData: GroceryItem[] = [
  // Mejeri (most common first)
  { name: "mjölk", category: "Mejeri", common: true },
  { name: "standardmjölk", category: "Mejeri", aliases: ["mellanmjölk"], common: true },
  { name: "lättmjölk", category: "Mejeri", common: true },
  { name: "minimjölk", category: "Mejeri", common: false },
  { name: "skummjölk", category: "Mejeri", common: false },
  { name: "filmjölk", category: "Mejeri", common: true },
  { name: "lättfil", category: "Mejeri", common: true },
  { name: "A-fil", category: "Mejeri", common: true },
  { name: "yoghurt", category: "Mejeri", common: true },
  { name: "naturell yoghurt", category: "Mejeri", common: true },
  { name: "grekisk yoghurt", category: "Mejeri", common: true },
  { name: "turkisk yoghurt", category: "Mejeri", common: true },
  { name: "smör", category: "Mejeri", common: true },
  { name: "bregott", category: "Mejeri", common: true },
  { name: "lätt & lagom", category: "Mejeri", common: true },
  { name: "margarin", category: "Mejeri", common: true },
  { name: "flora", category: "Mejeri", common: false },
  { name: "becel", category: "Mejeri", common: false },
  { name: "ost", category: "Mejeri", common: true },
  { name: "ost skivad", category: "Mejeri", common: true },
  { name: "ost bit", category: "Mejeri", common: true },
  { name: "riven ost", category: "Mejeri", common: true },
  { name: "västerbottenost", category: "Mejeri", common: true },
  { name: "grevé", category: "Mejeri", common: true },
  { name: "herrgård", category: "Mejeri", common: true },
  { name: "präst", category: "Mejeri", common: true },
  { name: "hushållsost", category: "Mejeri", common: true },
  { name: "mozzarella", category: "Mejeri", common: true },
  { name: "cheddar", category: "Mejeri", common: true },
  { name: "parmesanost", category: "Mejeri", common: true },
  { name: "fetaost", category: "Mejeri", common: true },
  { name: "getost", category: "Mejeri", common: false },
  { name: "brie", category: "Mejeri", common: false },
  { name: "camembert", category: "Mejeri", common: false },
  { name: "grädde", category: "Mejeri", common: true },
  { name: "vispgrädde", category: "Mejeri", common: true },
  { name: "matlagningsgrädde", category: "Mejeri", common: true },
  { name: "lättgrädde", category: "Mejeri", common: false },
  { name: "gräddfil", category: "Mejeri", common: true },
  { name: "kvarg", category: "Mejeri", common: true },
  { name: "lättkvarg", category: "Mejeri", common: true },
  { name: "kesella", category: "Mejeri", common: true },
  { name: "creme fraiche", category: "Mejeri", aliases: ["créme fraiche", "creme"], common: true },
  { name: "philadelphia", category: "Mejeri", common: true },
  { name: "färskost", category: "Mejeri", common: true },
  { name: "keso", category: "Mejeri", common: true },
  { name: "ricotta", category: "Mejeri", common: false },
  { name: "mascarpone", category: "Mejeri", common: false },
  { name: "créme bonjour", category: "Mejeri", common: false },
  { name: "ägg", category: "Mejeri", common: true },
  { name: "frigående ägg", category: "Mejeri", common: true },
  { name: "ekologiska ägg", category: "Mejeri", common: true },

  // Växtbaserade alternativ
  { name: "havremjölk", category: "Växtbaserat", common: true },
  { name: "sojamjölk", category: "Växtbaserat", common: true },
  { name: "mandelmjölk", category: "Växtbaserat", common: true },
  { name: "kokosmjölk dryck", category: "Växtbaserat", common: false },
  { name: "rismjölk", category: "Växtbaserat", common: false },
  { name: "havrefilmjölk", category: "Växtbaserat", common: false },
  { name: "sojayoghurt", category: "Växtbaserat", common: false },
  { name: "havreyoghurt", category: "Växtbaserat", common: false },
  { name: "växtbaserat smör", category: "Växtbaserat", common: false },
  { name: "växtbaserad grädde", category: "Växtbaserat", common: false },
  { name: "växtbaserad ost", category: "Växtbaserat", common: false },
  { name: "tofu", category: "Växtbaserat", common: true },
  { name: "tempeh", category: "Växtbaserat", common: false },
  { name: "quorn", category: "Växtbaserat", common: true },
  { name: "vegobullar", category: "Växtbaserat", common: true },

  // Frukt
  { name: "bananer", category: "Frukt", aliases: ["banan"], common: true },
  { name: "ekologiska bananer", category: "Frukt", common: false },
  { name: "äpplen", category: "Frukt", aliases: ["äpple"], common: true },
  { name: "royal gala", category: "Frukt", common: false },
  { name: "granny smith", category: "Frukt", common: false },
  { name: "golden delicious", category: "Frukt", common: false },
  { name: "apelsiner", category: "Frukt", aliases: ["apelsin"], common: true },
  { name: "blodapelsin", category: "Frukt", common: false },
  { name: "päron", category: "Frukt", common: true },
  { name: "kiwi", category: "Frukt", common: true },
  { name: "vindruvor", category: "Frukt", common: true },
  { name: "gröna vindruvor", category: "Frukt", common: false },
  { name: "röda vindruvor", category: "Frukt", common: false },
  { name: "clementin", category: "Frukt", aliases: ["clementiner"], common: true },
  { name: "satsumas", category: "Frukt", common: true },
  { name: "mandariner", category: "Frukt", common: true },
  { name: "grapefrukt", category: "Frukt", common: true },
  { name: "lime", category: "Frukt", common: true },
  { name: "citron", category: "Frukt", common: true },
  { name: "melon", category: "Frukt", common: true },
  { name: "vattenmelon", category: "Frukt", common: true },
  { name: "honungsmelon", category: "Frukt", common: true },
  { name: "galiamelon", category: "Frukt", common: false },
  { name: "cantaloupe", category: "Frukt", common: false },
  { name: "mango", category: "Frukt", common: true },
  { name: "ananas", category: "Frukt", common: true },
  { name: "jordgubbar", category: "Frukt", common: true },
  { name: "blåbär", category: "Frukt", common: true },
  { name: "hallon", category: "Frukt", common: true },
  { name: "björnbär", category: "Frukt", common: true },
  { name: "tranbär", category: "Frukt", common: false },
  { name: "lingon", category: "Frukt", common: true },
  { name: "krusbär", category: "Frukt", common: false },
  { name: "vinbär", category: "Frukt", common: false },
  { name: "svarta vinbär", category: "Frukt", common: false },
  { name: "röda vinbär", category: "Frukt", common: false },
  { name: "körsbär", category: "Frukt", common: true },
  { name: "plommon", category: "Frukt", common: true },
  { name: "persika", category: "Frukt", common: true },
  { name: "nektarin", category: "Frukt", common: true },
  { name: "aprikoser", category: "Frukt", common: false },
  { name: "avokado", category: "Frukt", common: true },
  { name: "passionsfrukt", category: "Frukt", common: false },
  { name: "papaya", category: "Frukt", common: false },
  { name: "dragon fruit", category: "Frukt", common: false },
  { name: "granatäpple", category: "Frukt", common: false },
  { name: "fikon", category: "Frukt", common: false },
  { name: "dadlar", category: "Frukt", common: false },
  { name: "russin", category: "Frukt", common: true },
  { name: "katrinplommon", category: "Frukt", common: false },

  // Grönsaker
  { name: "tomater", category: "Grönsaker", aliases: ["tomat"], common: true },
  { name: "cherry tomater", category: "Grönsaker", aliases: ["körsbärstomater"], common: true },
  { name: "plommontomat", category: "Grönsaker", common: true },
  { name: "beef tomater", category: "Grönsaker", common: false },
  { name: "gurka", category: "Grönsaker", common: true },
  { name: "minigurka", category: "Grönsaker", common: false },
  { name: "paprika", category: "Grönsaker", common: true },
  { name: "röd paprika", category: "Grönsaker", common: true },
  { name: "gul paprika", category: "Grönsaker", common: true },
  { name: "grön paprika", category: "Grönsaker", common: true },
  { name: "orange paprika", category: "Grönsaker", common: false },
  { name: "spetspaprika", category: "Grönsaker", common: false },
  { name: "chili", category: "Grönsaker", common: true },
  { name: "jalapeno", category: "Grönsaker", common: false },
  { name: "lök", category: "Grönsaker", common: true },
  { name: "gul lök", category: "Grönsaker", common: true },
  { name: "rödlök", category: "Grönsaker", common: true },
  { name: "schalottenlök", category: "Grönsaker", common: false },
  { name: "salladslök", category: "Grönsaker", common: true },
  { name: "purjolök", category: "Grönsaker", common: true },
  { name: "vitlök", category: "Grönsaker", common: true },
  { name: "morötter", category: "Grönsaker", aliases: ["morot"], common: true },
  { name: "babymortötter", category: "Grönsaker", common: false },
  { name: "potatis", category: "Grönsaker", common: true },
  { name: "fast potatis", category: "Grönsaker", common: true },
  { name: "mjölig potatis", category: "Grönsaker", common: true },
  { name: "röd potatis", category: "Grönsaker", common: false },
  { name: "färskpotatis", category: "Grönsaker", common: true },
  { name: "sötpotatis", category: "Grönsaker", common: true },
  { name: "sallad", category: "Grönsaker", common: true },
  { name: "isbergssallad", category: "Grönsaker", common: true },
  { name: "romana sallad", category: "Grönsaker", common: false },
  { name: "ruccola", category: "Grönsaker", aliases: ["rucola"], common: true },
  { name: "babyspenat", category: "Grönsaker", common: true },
  { name: "mixsallad", category: "Grönsaker", common: true },
  { name: "broccoli", category: "Grönsaker", common: true },
  { name: "blomkål", category: "Grönsaker", common: true },
  { name: "romanesco", category: "Grönsaker", common: false },
  { name: "spenat", category: "Grönsaker", common: true },
  { name: "zucchini", category: "Grönsaker", common: true },
  { name: "aubergine", category: "Grönsaker", common: true },
  { name: "squash", category: "Grönsaker", common: true },
  { name: "pumpa", category: "Grönsaker", common: true },
  { name: "butternut squash", category: "Grönsaker", common: false },
  { name: "majs", category: "Grönsaker", common: true },
  { name: "majskolv", category: "Grönsaker", common: false },
  { name: "ärtor", category: "Grönsaker", common: true },
  { name: "sockerärtor", category: "Grönsaker", common: false },
  { name: "böror", category: "Grönsaker", common: true },
  { name: "haricots verts", category: "Grönsaker", common: false },
  { name: "brysselkål", category: "Grönsaker", common: false },
  { name: "vitkål", category: "Grönsaker", common: true },
  { name: "rödkål", category: "Grönsaker", common: true },
  { name: "kålrot", category: "Grönsaker", common: true },
  { name: "rotselleri", category: "Grönsaker", common: false },
  { name: "selleri", category: "Grönsaker", common: true },
  { name: "stjälkselleri", category: "Grönsaker", common: false },
  { name: "palsternacka", category: "Grönsaker", common: false },
  { name: "rädisor", category: "Grönsaker", common: false },
  { name: "rova", category: "Grönsaker", common: false },
  { name: "rödbetor", category: "Grönsaker", common: true },
  { name: "kokta rödbetor", category: "Grönsaker", common: true },
  { name: "fänkål", category: "Grönsaker", common: false },
  { name: "kronärtskocka", category: "Grönsaker", common: false },
  { name: "sparris", category: "Grönsaker", common: true },
  { name: "grön sparris", category: "Grönsaker", common: true },
  { name: "vit sparris", category: "Grönsaker", common: false },
  { name: "bambuskott", category: "Grönsaker", common: false },
  { name: "bean sprouts", category: "Grönsaker", aliases: ["groddar"], common: false },
  { name: "pak choi", category: "Grönsaker", common: false },
  { name: "kinesiska kål", category: "Grönsaker", common: false },

  // Kött
  { name: "köttfärs", category: "Kött", common: true },
  { name: "nötfärs", category: "Kött", common: true },
  { name: "blandfärs", category: "Kött", common: true },
  { name: "fläskfärs", category: "Kött", common: false },
  { name: "kycklingfärs", category: "Kött", common: true },
  { name: "kalkonsfärs", category: "Kött", common: false },
  { name: "kycklingfilé", category: "Kött", aliases: ["kyckling"], common: true },
  { name: "kycklingbröst", category: "Kött", common: true },
  { name: "kycklinglårfilé", category: "Kött", common: true },
  { name: "kycklinglår", category: "Kött", common: true },
  { name: "kycklingvingar", category: "Kött", common: true },
  { name: "hel kyckling", category: "Kött", common: true },
  { name: "kyckling innerfilé", category: "Kött", common: false },
  { name: "kalkonfilé", category: "Kött", common: false },
  { name: "fläskfilé", category: "Kött", common: true },
  { name: "fläskkotlett", category: "Kött", common: true },
  { name: "fläskkarré", category: "Kött", common: true },
  { name: "revbensspjäll", category: "Kött", common: true },
  { name: "sidfläsk", category: "Kött", common: true },
  { name: "bacon", category: "Kött", common: true },
  { name: "skivad bacon", category: "Kött", common: true },
  { name: "bacon tärnad", category: "Kött", common: true },
  { name: "skinka", category: "Kött", common: true },
  { name: "rökt skinka", category: "Kött", common: true },
  { name: "prosciutto", category: "Kött", common: false },
  { name: "serrano", category: "Kött", common: false },
  { name: "salami", category: "Kött", common: true },
  { name: "chorizo", category: "Kött", common: true },
  { name: "pepperoni", category: "Kött", common: true },
  { name: "korv", category: "Kött", common: true },
  { name: "falukorv", category: "Kött", common: true },
  { name: "prinskorv", category: "Kött", common: true },
  { name: "isterband", category: "Kött", common: true },
  { name: "bratwurst", category: "Kött", common: false },
  { name: "grillkorv", category: "Kött", common: true },
  { name: "köttbullar", category: "Kött", common: true },
  { name: "fläskbullar", category: "Kött", common: false },
  { name: "kycklingbullar", category: "Kött", common: false },
  { name: "biff", category: "Kött", common: true },
  { name: "entrecôte", category: "Kött", common: true },
  { name: "ryggbiff", category: "Kött", common: true },
  { name: "fransyska", category: "Kött", common: true },
  { name: "oxfilé", category: "Kött", common: false },
  { name: "oxstek", category: "Kött", common: true },
  { name: "kassler", category: "Kött", common: true },
  { name: "fläskstek", category: "Kött", common: true },
  { name: "lamm", category: "Kött", common: false },
  { name: "lammfilé", category: "Kött", common: false },
  { name: "lammkotlett", category: "Kött", common: false },
  { name: "lammracks", category: "Kött", common: false },
  { name: "lammstek", category: "Kött", common: false },
  { name: "älg", category: "Kött", common: false },
  { name: "ren", category: "Kött", common: false },
  { name: "vildsvin", category: "Kött", common: false },

  // Fisk & Skaldjur
  { name: "lax", category: "Fisk", common: true },
  { name: "laxfilé", category: "Fisk", common: true },
  { name: "gravlax", category: "Fisk", common: true },
  { name: "rökt lax", category: "Fisk", common: true },
  { name: "regnbåge", category: "Fisk", common: true },
  { name: "torsk", category: "Fisk", common: true },
  { name: "torskfilé", category: "Fisk", common: true },
  { name: "torskrygg", category: "Fisk", common: true },
  { name: "kolja", category: "Fisk", common: true },
  { name: "kolja filé", category: "Fisk", common: true },
  { name: "sej", category: "Fisk", common: true },
  { name: "sejfilé", category: "Fisk", common: true },
  { name: "hälleflundra", category: "Fisk", common: false },
  { name: "rödspätta", category: "Fisk", common: false },
  { name: "piggvar", category: "Fisk", common: false },
  { name: "aborre", category: "Fisk", common: false },
  { name: "gös", category: "Fisk", common: false },
  { name: "gädda", category: "Fisk", common: false },
  { name: "sill", category: "Fisk", common: true },
  { name: "sillfilé", category: "Fisk", common: true },
  { name: "inlagd sill", category: "Fisk", common: true },
  { name: "matjessill", category: "Fisk", common: true },
  { name: "strömming", category: "Fisk", common: false },
  { name: "ål", category: "Fisk", common: false },
  { name: "tonfisk", category: "Fisk", common: true },
  { name: "makrill", category: "Fisk", common: true },
  { name: "räkor", category: "Fisk", common: true },
  { name: "skalade räkor", category: "Fisk", common: true },
  { name: "hummersås", category: "Fisk", common: false },
  { name: "musslor", category: "Fisk", common: true },
  { name: "blåmusslor", category: "Fisk", common: true },
  { name: "ostron", category: "Fisk", common: false },
  { name: "krabba", category: "Fisk", common: false },
  { name: "hummer", category: "Fisk", common: false },
  { name: "kräftor", category: "Fisk", common: false },
  { name: "fisksoppa", category: "Fisk", common: false },
  { name: "fiskbullar", category: "Fisk", common: true },
  { name: "fiskpinnar", category: "Fisk", common: true },
  { name: "fiskgratäng", category: "Fisk", common: true },
  { name: "surströmming", category: "Fisk", common: false },
  { name: "ansjovis", category: "Fisk", common: true },
  { name: "sardiner", category: "Fisk", common: false },
  { name: "kaviar", category: "Fisk", common: true },
  { name: "kalles kaviar", category: "Fisk", common: true },
  { name: "rom", category: "Fisk", common: false },
  { name: "löjrom", category: "Fisk", common: false },

  // Bröd & Bakverk
  { name: "bröd", category: "Bröd", common: true },
  { name: "formbröd", category: "Bröd", common: true },
  { name: "skivat bröd", category: "Bröd", common: true },
  { name: "limpa", category: "Bröd", common: true },
  { name: "rågbröd", category: "Bröd", common: true },
  { name: "knäckebröd", category: "Bröd", common: true },
  { name: "råg-crisp", category: "Bröd", common: true },
  { name: "frallor", category: "Bröd", common: true },
  { name: "hamburgerbröd", category: "Bröd", common: true },
  { name: "hot dog bröd", category: "Bröd", common: true },
  { name: "ciabatta", category: "Bröd", common: true },
  { name: "focaccia", category: "Bröd", common: false },
  { name: "pitabröd", category: "Bröd", common: true },
  { name: "tunnbröd", category: "Bröd", common: true },
  { name: "polarbröd", category: "Bröd", common: true },
  { name: "tortilla", category: "Bröd", common: true },
  { name: "wraps", category: "Bröd", common: true },
  { name: "naanbröd", category: "Bröd", common: true },
  { name: "bagel", category: "Bröd", common: false },
  { name: "croissant", category: "Bröd", common: true },
  { name: "pain au chocolat", category: "Bröd", common: false },
  { name: "kanelbulle", category: "Bröd", common: true },
  { name: "wienerbröd", category: "Bröd", common: true },
  { name: "skorpor", category: "Bröd", common: true },
  { name: "kavring", category: "Bröd", common: true },

  // Pasta & Ris & Spannmål
  { name: "pasta", category: "Pasta & Ris", common: true },
  { name: "spaghetti", category: "Pasta & Ris", common: true },
  { name: "penne", category: "Pasta & Ris", common: true },
  { name: "fusilli", category: "Pasta & Ris", common: true },
  { name: "farfalle", category: "Pasta & Ris", common: false },
  { name: "tagliatelle", category: "Pasta & Ris", common: true },
  { name: "fettuccine", category: "Pasta & Ris", common: false },
  { name: "makaroner", category: "Pasta & Ris", common: true },
  { name: "lasagneplattor", category: "Pasta & Ris", common: true },
  { name: "cannelloni", category: "Pasta & Ris", common: false },
  { name: "ravioli", category: "Pasta & Ris", common: true },
  { name: "tortellini", category: "Pasta & Ris", common: true },
  { name: "gnocchi", category: "Pasta & Ris", common: true },
  { name: "ris", category: "Pasta & Ris", common: true },
  { name: "jasminris", category: "Pasta & Ris", common: true },
  { name: "basmatiris", category: "Pasta & Ris", common: true },
  { name: "risoni", category: "Pasta & Ris", common: false },
  { name: "arborio ris", category: "Pasta & Ris", common: false },
  { name: "sushiris", category: "Pasta & Ris", common: true },
  { name: "fullkornsris", category: "Pasta & Ris", common: true },
  { name: "svart ris", category: "Pasta & Ris", common: false },
  { name: "risotto", category: "Pasta & Ris", common: true },
  { name: "bulgur", category: "Pasta & Ris", common: true },
  { name: "couscous", category: "Pasta & Ris", common: true },
  { name: "quinoa", category: "Pasta & Ris", common: true },
  { name: "linser", category: "Pasta & Ris", common: true },
  { name: "röda linser", category: "Pasta & Ris", common: true },
  { name: "gröna linser", category: "Pasta & Ris", common: false },
  { name: "kikärtor", category: "Pasta & Ris", common: true },
  { name: "svarta bönor", category: "Pasta & Ris", common: true },
  { name: "vita bönor", category: "Pasta & Ris", common: true },
  { name: "kidneybönor", category: "Pasta & Ris", common: true },

  // Frukostflingor & Müsli
  { name: "frukostflingor", category: "Frukost", aliases: ["flingor"], common: true },
  { name: "cornflakes", category: "Frukost", common: true },
  { name: "frosties", category: "Frukost", common: true },
  { name: "special k", category: "Frukost", common: true },
  { name: "coco pops", category: "Frukost", common: true },
  { name: "müsli", category: "Frukost", common: true },
  { name: "granola", category: "Frukost", common: true },
  { name: "havregryn", category: "Frukost", common: true },
  { name: "havrefras", category: "Frukost", common: true },
  { name: "havregrynsgröt", category: "Frukost", common: true },
  { name: "blå flingor", category: "Frukost", common: false },
  { name: "smacks", category: "Frukost", common: true },
  { name: "fiberhavre", category: "Frukost", common: false },

  // Bakning & Mjöl
  { name: "mjöl", category: "Bakning", common: true },
  { name: "vetemjöl", category: "Bakning", common: true },
  { name: "grovt mjöl", category: "Bakning", common: true },
  { name: "rågsikt", category: "Bakning", common: true },
  { name: "rågmjöl", category: "Bakning", common: true },
  { name: "dinkel", category: "Bakning", common: false },
  { name: "dinkelmjöl", category: "Bakning", common: false },
  { name: "mandelmjöl", category: "Bakning", common: false },
  { name: "kokosmjöl", category: "Bakning", common: false },
  { name: "majsmjöl", category: "Bakning", aliases: ["maizena"], common: true },
  { name: "potatismjöl", category: "Bakning", common: true },
  { name: "bakpulver", category: "Bakning", common: true },
  { name: "bikarbonat", category: "Bakning", common: true },
  { name: "jäst", category: "Bakning", common: true },
  { name: "torrjäst", category: "Bakning", common: true },
  { name: "färsk jäst", category: "Bakning", common: true },
  { name: "vaniljsocker", category: "Bakning", common: true },
  { name: "vanilj", category: "Bakning", common: true },
  { name: "vaniljstång", category: "Bakning", common: false },
  { name: "vaniljextrakt", category: "Bakning", common: false },
  { name: "florsocker", category: "Bakning", common: true },
  { name: "pärlsocker", category: "Bakning", common: true },
  { name: "strössel", category: "Bakning", common: true },
  { name: "kakao", category: "Bakning", common: true },
  { name: "choklad", category: "Bakning", common: true },
  { name: "mörk choklad", category: "Bakning", common: true },
  { name: "mjölkchoklad", category: "Bakning", common: true },
  { name: "vit choklad", category: "Bakning", common: true },
  { name: "chokladknappar", category: "Bakning", common: true },
  { name: "gelatinpulver", category: "Bakning", common: true },
  { name: "gelatin", category: "Bakning", common: true },
  { name: "agar agar", category: "Bakning", common: false },

  // Skafferi - Kryddor & Örter
  { name: "salt", category: "Kryddor", common: true },
  { name: "havssalt", category: "Kryddor", common: true },
  { name: "flingsalt", category: "Kryddor", common: false },
  { name: "peppar", category: "Kryddor", common: true },
  { name: "svartpeppar", category: "Kryddor", common: true },
  { name: "vitpeppar", category: "Kryddor", common: true },
  { name: "cayennepeppar", category: "Kryddor", common: true },
  { name: "paprikapulver", category: "Kryddor", common: true },
  { name: "rökt paprika", category: "Kryddor", common: false },
  { name: "spiskummin", category: "Kryddor", common: true },
  { name: "koriander", category: "Kryddor", common: true },
  { name: "kanel", category: "Kryddor", common: true },
  { name: "kardemumma", category: "Kryddor", common: true },
  { name: "ingefära", category: "Kryddor", common: true },
  { name: "färsk ingefära", category: "Kryddor", common: true },
  { name: "ingefärspulver", category: "Kryddor", common: true },
  { name: "curry", category: "Kryddor", common: true },
  { name: "currypasta", category: "Kryddor", common: true },
  { name: "garam masala", category: "Kryddor", common: false },
  { name: "gurkmeja", category: "Kryddor", common: true },
  { name: "chilipulver", category: "Kryddor", common: true },
  { name: "chiliflingor", category: "Kryddor", common: true },
  { name: "oregano", category: "Kryddor", common: true },
  { name: "basilika", category: "Kryddor", common: true },
  { name: "färsk basilika", category: "Kryddor", common: true },
  { name: "timjan", category: "Kryddor", common: true },
  { name: "rosmarin", category: "Kryddor", common: true },
  { name: "salvia", category: "Kryddor", common: false },
  { name: "dragon", category: "Kryddor", common: false },
  { name: "mejram", category: "Kryddor", common: false },
  { name: "dill", category: "Kryddor", common: true },
  { name: "färsk dill", category: "Kryddor", common: true },
  { name: "gräslök", category: "Kryddor", common: true },
  { name: "persilja", category: "Kryddor", common: true },
  { name: "färsk persilja", category: "Kryddor", common: true },
  { name: "koriander färsk", category: "Kryddor", common: true },
  { name: "mynta", category: "Kryddor", common: true },
  { name: "färsk mynta", category: "Kryddor", common: true },
  { name: "citrongräs", category: "Kryddor", common: false },
  { name: "lagerblad", category: "Kryddor", common: true },
  { name: "kryddpeppar", category: "Kryddor", common: true },
  { name: "nejlikor", category: "Kryddor", common: true },
  { name: "spiskummin hel", category: "Kryddor", common: false },
  { name: "senapskorn", category: "Kryddor", common: false },
  { name: "fänkålsfrö", category: "Kryddor", common: false },
  { name: "sesam", category: "Kryddor", common: true },
  { name: "sesamfrö", category: "Kryddor", common: true },
  { name: "vallmofrö", category: "Kryddor", common: false },
  { name: "linfrö", category: "Kryddor", common: true },
  { name: "chiafrö", category: "Kryddor", common: true },
  { name: "pumpafrö", category: "Kryddor", common: true },
  { name: "solrosfrö", category: "Kryddor", common: true },

  // Skafferi - Oljor & Såser
  { name: "socker", category: "Skafferi", common: true },
  { name: "strösocker", category: "Skafferi", common: true },
  { name: "farinsocker", category: "Skafferi", common: true },
  { name: "muscovado", category: "Skafferi", common: false },
  { name: "honung", category: "Skafferi", common: true },
  { name: "sirap", category: "Skafferi", common: true },
  { name: "ljus sirap", category: "Skafferi", common: true },
  { name: "mörk sirap", category: "Skafferi", common: true },
  { name: "lönnsirap", category: "Skafferi", common: true },
  { name: "agavesirap", category: "Skafferi", common: false },
  { name: "olivolja", category: "Skafferi", common: true },
  { name: "extra virgin olivolja", category: "Skafferi", common: true },
  { name: "rapsolja", category: "Skafferi", common: true },
  { name: "solrosolja", category: "Skafferi", common: true },
  { name: "sesamolja", category: "Skafferi", common: true },
  { name: "kokosolja", category: "Skafferi", common: true },
  { name: "avokadoolja", category: "Skafferi", common: false },
  { name: "ättika", category: "Skafferi", common: true },
  { name: "ättikssprit", category: "Skafferi", common: true },
  { name: "vinäger", category: "Skafferi", common: true },
  { name: "vit vinäger", category: "Skafferi", common: true },
  { name: "rödvinsvinäger", category: "Skafferi", common: true },
  { name: "vitvinsvinäger", category: "Skafferi", common: true },
  { name: "balsamico", category: "Skafferi", common: true },
  { name: "äppelcidervinäger", category: "Skafferi", common: true },
  { name: "risvinäger", category: "Skafferi", common: false },
  { name: "ketchup", category: "Skafferi", common: true },
  { name: "majonnäs", category: "Skafferi", common: true },
  { name: "senap", category: "Skafferi", common: true },
  { name: "dijonsenap", category: "Skafferi", common: true },
  { name: "grov senap", category: "Skafferi", common: true },
  { name: "soja", category: "Skafferi", aliases: ["sojasås"], common: true },
  { name: "sweet chili", category: "Skafferi", common: true },
  { name: "chilisås", category: "Skafferi", common: true },
  { name: "sriracha", category: "Skafferi", common: true },
  { name: "tabasco", category: "Skafferi", common: true },
  { name: "worcestersås", category: "Skafferi", common: true },
  { name: "HP sås", category: "Skafferi", common: true },
  { name: "BBQ sås", category: "Skafferi", common: true },
  { name: "tomatpuré", category: "Skafferi", common: true },
  { name: "tomatketchup", category: "Skafferi", common: true },
  { name: "bostongurka", category: "Skafferi", common: true },
  { name: "sylt", category: "Skafferi", common: true },
  { name: "jordgubbssylt", category: "Skafferi", common: true },
  { name: "hallonsylt", category: "Skafferi", common: true },
  { name: "aprikossylt", category: "Skafferi", common: false },
  { name: "marmelad", category: "Skafferi", common: true },
  { name: "apelsinmarmelad", category: "Skafferi", common: true },
  { name: "jordnötssmör", category: "Skafferi", common: true },
  { name: "nutella", category: "Skafferi", common: true },
  { name: "pesto", category: "Skafferi", common: true },
  { name: "grön pesto", category: "Skafferi", common: true },
  { name: "röd pesto", category: "Skafferi", common: true },
  { name: "hummus", category: "Skafferi", common: true },
  { name: "guacamole", category: "Skafferi", common: true },
  { name: "salsa", category: "Skafferi", common: true },
  { name: "ajvar", category: "Skafferi", common: false },
  { name: "tahin", category: "Skafferi", common: false },
  { name: "miso", category: "Skafferi", common: false },
  { name: "fisksås", category: "Skafferi", common: true },
  { name: "ostronsås", category: "Skafferi", common: true },
  { name: "hoisinsås", category: "Skafferi", common: false },
  { name: "teriyakisås", category: "Skafferi", common: true },

  // Konserver & Burkar
  { name: "tomatkross", category: "Konserver", common: true },
  { name: "krossade tomater", category: "Konserver", common: true },
  { name: "hela tomater", category: "Konserver", common: true },
  { name: "passerade tomater", category: "Konserver", common: true },
  { name: "tomatpuré burk", category: "Konserver", common: true },
  { name: "körsbärstomater burk", category: "Konserver", common: false },
  { name: "soltorkade tomater", category: "Konserver", common: true },
  { name: "tonfisk burk", category: "Konserver", common: true },
  { name: "tonfisk i vatten", category: "Konserver", common: true },
  { name: "tonfisk i olja", category: "Konserver", common: true },
  { name: "makrill burk", category: "Konserver", common: true },
  { name: "sardiner", category: "Konserver", common: false },
  { name: "ansjovis burk", category: "Konserver", common: true },
  { name: "räkor burk", category: "Konserver", common: true },
  { name: "kikärtor burk", category: "Konserver", common: true },
  { name: "kidneybönor burk", category: "Konserver", common: true },
  { name: "vita bönor burk", category: "Konserver", common: true },
  { name: "svarta bönor burk", category: "Konserver", common: true },
  { name: "linser burk", category: "Konserver", common: true },
  { name: "majs burk", category: "Konserver", common: true },
  { name: "ärtor burk", category: "Konserver", common: true },
  { name: "champinjoner burk", category: "Konserver", common: true },
  { name: "kronärtskocka burk", category: "Konserver", common: false },
  { name: "kokosmjölk", category: "Konserver", common: true },
  { name: "kokosmjölk burk", category: "Konserver", common: true },
  { name: "kokosgrädde", category: "Konserver", common: true },
  { name: "kokos", category: "Konserver", common: true },
  { name: "riven kokos", category: "Konserver", common: true },
  { name: "bambu burk", category: "Konserver", common: false },
  { name: "oliver", category: "Konserver", common: true },
  { name: "gröna oliver", category: "Konserver", common: true },
  { name: "svarta oliver", category: "Konserver", common: true },
  { name: "kapris", category: "Konserver", common: true },
  { name: "jalapenos burk", category: "Konserver", common: true },
  { name: "pickles", category: "Konserver", common: false },

  // Dryck - Varm
  { name: "kaffe", category: "Dryck", common: true },
  { name: "kaffebönor", category: "Dryck", common: true },
  { name: "bryggkaffe", category: "Dryck", common: true },
  { name: "snabbkaffe", category: "Dryck", common: true },
  { name: "espresso", category: "Dryck", common: true },
  { name: "koffeinfritt kaffe", category: "Dryck", common: false },
  { name: "te", category: "Dryck", common: true },
  { name: "svart te", category: "Dryck", common: true },
  { name: "grönt te", category: "Dryck", common: true },
  { name: "rooibos", category: "Dryck", common: false },
  { name: "kamomillte", category: "Dryck", common: true },
  { name: "earl grey", category: "Dryck", common: true },
  { name: "engelska breakfast", category: "Dryck", common: false },
  { name: "örtte", category: "Dryck", common: true },
  { name: "myntte", category: "Dryck", common: true },
  { name: "chai", category: "Dryck", common: true },
  { name: "matcha", category: "Dryck", common: false },
  { name: "kakao", category: "Dryck", common: true },
  { name: "chokladdryck", category: "Dryck", common: true },
  { name: "o'boy", category: "Dryck", common: true },

  // Dryck - Kall
  { name: "juice", category: "Dryck", common: true },
  { name: "apelsinjuice", category: "Dryck", common: true },
  { name: "äppeljuice", category: "Dryck", common: true },
  { name: "multivitaminjuice", category: "Dryck", common: true },
  { name: "ananasjuice", category: "Dryck", common: false },
  { name: "tranbärsjuice", category: "Dryck", common: true },
  { name: "tomatjuice", category: "Dryck", common: true },
  { name: "smoothie", category: "Dryck", common: true },
  { name: "läsk", category: "Dryck", common: true },
  { name: "coca cola", category: "Dryck", common: true },
  { name: "pepsi", category: "Dryck", common: true },
  { name: "fanta", category: "Dryck", common: true },
  { name: "sprite", category: "Dryck", common: true },
  { name: "sockerfri läsk", category: "Dryck", common: true },
  { name: "coca cola zero", category: "Dryck", common: true },
  { name: "festis", category: "Dryck", common: true },
  { name: "zingo", category: "Dryck", common: true },
  { name: "trocadero", category: "Dryck", common: true },
  { name: "sockerdricka", category: "Dryck", common: true },
  { name: "vatten", category: "Dryck", common: true },
  { name: "mineralvatten", category: "Dryck", common: true },
  { name: "ramlösa", category: "Dryck", common: true },
  { name: "loka", category: "Dryck", common: true },
  { name: "perrier", category: "Dryck", common: false },
  { name: "kolsyrat vatten", category: "Dryck", common: true },
  { name: "energidryck", category: "Dryck", common: true },
  { name: "red bull", category: "Dryck", common: true },
  { name: "monster", category: "Dryck", common: true },
  { name: "battery", category: "Dryck", common: false },
  { name: "sportdryck", category: "Dryck", common: true },
  { name: "powerade", category: "Dryck", common: true },
  { name: "gatorade", category: "Dryck", common: false },
  { name: "öl", category: "Dryck", common: true },
  { name: "alkoholfritt öl", category: "Dryck", common: true },
  { name: "folköl", category: "Dryck", common: true },
  { name: "lättöl", category: "Dryck", common: true },
  { name: "cider", category: "Dryck", common: true },
  { name: "vin", category: "Dryck", common: true },
  { name: "rödvin", category: "Dryck", common: true },
  { name: "vitt vin", category: "Dryck", common: true },
  { name: "rosé", category: "Dryck", common: true },
  { name: "alkoholfritt vin", category: "Dryck", common: false },
  { name: "champagne", category: "Dryck", common: false },
  { name: "prosecco", category: "Dryck", common: false },

  // Godis & Snacks
  { name: "chips", category: "Snacks", common: true },
  { name: "sourcream chips", category: "Snacks", common: true },
  { name: "saltade chips", category: "Snacks", common: true },
  { name: "paprikachips", category: "Snacks", common: true },
  { name: "dip", category: "Snacks", common: true },
  { name: "sourcream dip", category: "Snacks", common: true },
  { name: "ostbågar", category: "Snacks", common: true },
  { name: "popcorn", category: "Snacks", common: true },
  { name: "mikrovågspopcorn", category: "Snacks", common: true },
  { name: "popcornkärnor", category: "Snacks", common: false },
  { name: "nötter", category: "Snacks", common: true },
  { name: "jordnötter", category: "Snacks", common: true },
  { name: "cashewnötter", category: "Snacks", common: true },
  { name: "mandlar", category: "Snacks", common: true },
  { name: "hasselnötter", category: "Snacks", common: true },
  { name: "valnötter", category: "Snacks", common: true },
  { name: "pistaschnötter", category: "Snacks", common: false },
  { name: "blandat nötter", category: "Snacks", common: true },
  { name: "rostade nötter", category: "Snacks", common: true },
  { name: "studentmat", category: "Snacks", common: true },
  { name: "fruktmix", category: "Snacks", common: false },
  { name: "torkad frukt", category: "Snacks", common: false },
  { name: "godis", category: "Snacks", common: true },
  { name: "lösgodis", category: "Snacks", common: true },
  { name: "choklad", category: "Snacks", common: true },
  { name: "marabou", category: "Snacks", common: true },
  { name: "kexchoklad", category: "Snacks", common: true },
  { name: "dumle", category: "Snacks", common: true },
  { name: "daim", category: "Snacks", common: true },
  { name: "snickers", category: "Snacks", common: true },
  { name: "twix", category: "Snacks", common: true },
  { name: "mars", category: "Snacks", common: true },
  { name: "kitkat", category: "Snacks", common: true },
  { name: "bounty", category: "Snacks", common: true },
  { name: "m&ms", category: "Snacks", common: true },
  { name: "lakritskonfekt", category: "Snacks", common: true },
  { name: "bilar", category: "Snacks", common: true },
  { name: "ahlgrens bilar", category: "Snacks", common: true },
  { name: "skumbananer", category: "Snacks", common: true },
  { name: "nappar", category: "Snacks", common: true },
  { name: "gelehallon", category: "Snacks", common: true },
  { name: "sura skallar", category: "Snacks", common: true },
  { name: "tutti frutti", category: "Snacks", common: true },
  { name: "wine gums", category: "Snacks", common: false },
  { name: "kola", category: "Snacks", common: true },
  { name: "polkagrisar", category: "Snacks", common: false },
  { name: "klubbor", category: "Snacks", common: true },
  { name: "halstabletter", category: "Snacks", common: false },
  { name: "tuggummi", category: "Snacks", common: true },
  { name: "mentos", category: "Snacks", common: true },
  { name: "kiss", category: "Snacks", common: true },
  { name: "geléhallon", category: "Snacks", common: true },
  { name: "kex", category: "Snacks", common: true },
  { name: "digestive", category: "Snacks", common: true },
  { name: "ballerina", category: "Snacks", common: true },
  { name: "göteborgs kex", category: "Snacks", common: true },
  { name: "prinsesskex", category: "Snacks", common: true },
  { name: "havrekex", category: "Snacks", common: true },
  { name: "maria kex", category: "Snacks", common: true },
  { name: "petit beurre", category: "Snacks", common: true },
  { name: "oreo", category: "Snacks", common: true },
  { name: "kakor", category: "Snacks", common: true },
  { name: "pepparkakor", category: "Snacks", common: true },
  { name: "saffranskaka", category: "Snacks", common: false },

  // Frysvaror
  { name: "glass", category: "Frys", common: true },
  { name: "vaniljglass", category: "Frys", common: true },
  { name: "chokladglass", category: "Frys", common: true },
  { name: "frysta bär", category: "Frys", common: true },
  { name: "frysta jordgubbar", category: "Frys", common: true },
  { name: "frysta hallon", category: "Frys", common: true },
  { name: "frysta blåbär", category: "Frys", common: true },
  { name: "frysta blandade bär", category: "Frys", common: true },
  { name: "frysta grönsaker", category: "Frys", common: true },
  { name: "frysta ärtor", category: "Frys", common: true },
  { name: "frysta bönor", category: "Frys", common: true },
  { name: "fryst broccoli", category: "Frys", common: true },
  { name: "fryst blomkål", category: "Frys", common: true },
  { name: "fryst spenat", category: "Frys", common: true },
  { name: "fryst wokgrönsaker", category: "Frys", common: true },
  { name: "fryst grönsaksmix", category: "Frys", common: true },
  { name: "pommes", category: "Frys", common: true },
  { name: "pommes frites", category: "Frys", common: true },
  { name: "wedges", category: "Frys", common: true },
  { name: "klyftpotatis", category: "Frys", common: true },
  { name: "halloumi fries", category: "Frys", common: false },
  { name: "pizza", category: "Frys", common: true },
  { name: "fryspizza", category: "Frys", common: true },
  { name: "nuggets", category: "Frys", common: true },
  { name: "chicken nuggets", category: "Frys", common: true },
  { name: "fiskpinnar", category: "Frys", common: true },
  { name: "pannkakor", category: "Frys", common: true },
  { name: "frysta pannkakor", category: "Frys", common: true },
  { name: "våfflor", category: "Frys", common: true },
  { name: "frysta våfflor", category: "Frys", common: true },

  // Hygien & Städ
  { name: "toalettpapper", category: "Hygien", aliases: ["toapapper"], common: true },
  { name: "hushållspapper", category: "Hygien", common: true },
  { name: "diskmedel", category: "Hygien", common: true },
  { name: "diskborste", category: "Hygien", common: true },
  { name: "disktrasa", category: "Hygien", common: true },
  { name: "svamp", category: "Hygien", common: true },
  { name: "disksvamp", category: "Hygien", common: true },
  { name: "disktabs", category: "Hygien", common: true },
  { name: "diskmaskinssalt", category: "Hygien", common: true },
  { name: "sköljmedel diskmaskin", category: "Hygien", common: true },
  { name: "tvål", category: "Hygien", common: true },
  { name: "handtvål", category: "Hygien", common: true },
  { name: "flytande tvål", category: "Hygien", common: true },
  { name: "tvålstycke", category: "Hygien", common: true },
  { name: "duschtvål", category: "Hygien", common: true },
  { name: "duschgel", category: "Hygien", common: true },
  { name: "schampo", category: "Hygien", common: true },
  { name: "balsam", category: "Hygien", common: true },
  { name: "hårinpackning", category: "Hygien", common: false },
  { name: "tandkräm", category: "Hygien", common: true },
  { name: "tandborste", category: "Hygien", common: true },
  { name: "munvatten", category: "Hygien", common: true },
  { name: "tandtråd", category: "Hygien", common: true },
  { name: "deodorant", category: "Hygien", common: true },
  { name: "rakblad", category: "Hygien", common: true },
  { name: "raklödder", category: "Hygien", common: false },
  { name: "rakgel", category: "Hygien", common: false },
  { name: "engångshyvlar", category: "Hygien", common: true },
  { name: "tvättmedel", category: "Hygien", common: true },
  { name: "sköljmedel", category: "Hygien", common: true },
  { name: "färgtvättmedel", category: "Hygien", common: true },
  { name: "vittvättmedel", category: "Hygien", common: true },
  { name: "fläckborttagning", category: "Hygien", common: true },
  { name: "rengöringsmedel", category: "Hygien", common: true },
  { name: "allrengörande", category: "Hygien", common: true },
  { name: "badrumsspray", category: "Hygien", common: true },
  { name: "WC-rens", category: "Hygien", common: true },
  { name: "fönsterputs", category: "Hygien", common: true },
  { name: "klorin", category: "Hygien", common: false },
  { name: "såpa", category: "Hygien", common: true },
  { name: "grönsåpa", category: "Hygien", common: true },
  { name: "dammsugarpåsar", category: "Hygien", common: true },
  { name: "soppåsar", category: "Hygien", common: true },
  { name: "fryspåsar", category: "Hygien", common: true },
  { name: "aluminiumfolie", category: "Hygien", common: true },
  { name: "plastfolie", category: "Hygien", common: true },
  { name: "bakplåtspapper", category: "Hygien", common: true },
  { name: "stearinljus", category: "Hygien", common: true },
  { name: "tändstickor", category: "Hygien", common: true },
  { name: "tändare", category: "Hygien", common: true },
  { name: "batterier", category: "Hygien", common: true },

  // Baby & Barn
  { name: "blöjor", category: "Baby", common: true },
  { name: "babyprodukter", category: "Baby", common: false },
  { name: "barnmat", category: "Baby", common: true },
  { name: "barnmat burk", category: "Baby", common: true },
  { name: "välling", category: "Baby", common: true },
  { name: "gröt baby", category: "Baby", common: true },
  { name: "fruktmos", category: "Baby", common: true },
  { name: "barnmjölk", category: "Baby", common: false },
  { name: "napp", category: "Baby", common: false },
  { name: "nappflaska", category: "Baby", common: false },
  { name: "våtservetter", category: "Baby", common: true },
  { name: "babyschampo", category: "Baby", common: false },

  // Djurmat
  { name: "kattmat", category: "Djur", common: true },
  { name: "hundmat", category: "Djur", common: true },
  { name: "hundgodis", category: "Djur", common: true },
  { name: "kattgodis", category: "Djur", common: true },
  { name: "kattströ", category: "Djur", common: true },
  { name: "fågelfrö", category: "Djur", common: false },

  // Övrigt
  { name: "grillkol", category: "Övrigt", common: true },
  { name: "tändvätska", category: "Övrigt", common: true },
  { name: "tändkuber", category: "Övrigt", common: true },
  { name: "glasspinnar", category: "Övrigt", common: false },
  { name: "sugrör", category: "Övrigt", common: true },
  { name: "servetter", category: "Övrigt", common: true },
  { name: "papperstallrikar", category: "Övrigt", common: true },
  { name: "engångsbestick", category: "Övrigt", common: false },
  { name: "engångsglas", category: "Övrigt", common: false },
];

// Extract product name from input like "två mjölk" or "300 g mjöl" -> "mjölk", "mjöl"
function extractProductName(input: string): string {
  const trimmed = input.trim();

  // Pattern: [amount] [unit] item
  // Examples: "4 apelsiner", "300g mjöl", "två mjölk"
  const match = trimmed.match(/^(\d+[,.]?\d*|\d+-\d+|en|ett|två|tre|fyra|fem|sex|sju|åtta|nio|tio)\s*([a-zåäö]+)?\s+(.+)$/i);

  if (match) {
    const [, , possibleUnit, item] = match;

    // Check if possibleUnit is a known unit
    const unitPattern = /^(st|stycken|styck|kg|kilo|g|gram|hg|hekto|l|liter|dl|deciliter|ml|msk|matsked|tsk|tesked|krm|påse|påsar|burk|burkar|paket|förp|förpackning)$/i;
    const isUnit = possibleUnit && unitPattern.test(possibleUnit);

    // If possibleUnit wasn't a unit, include it in the product name
    return isUnit ? item : (possibleUnit ? `${possibleUnit} ${item}` : item);
  }

  // No amount/unit found, return as-is
  return trimmed;
}

// Search function with fuzzy matching
export function searchGroceries(query: string, limit: number = 5): GroceryItem[] {
  if (!query || query.length < 2) return [];

  // Extract product name from query (e.g., "två mjölk" -> "mjölk")
  const productName = extractProductName(query);
  const normalizedQuery = productName.toLowerCase().trim();

  // Score each item
  const scored = groceryData.map(item => {
    let score = 0;
    const itemName = item.name.toLowerCase();

    // Exact match (highest priority)
    if (itemName === normalizedQuery) {
      score = 1000;
    }
    // Starts with query
    else if (itemName.startsWith(normalizedQuery)) {
      score = 100 + (item.common ? 50 : 0);
    }
    // Contains query
    else if (itemName.includes(normalizedQuery)) {
      score = 50 + (item.common ? 25 : 0);
    }
    // Check aliases
    else if (item.aliases?.some(alias => alias.toLowerCase().includes(normalizedQuery))) {
      score = 40 + (item.common ? 20 : 0);
    }

    // Boost common items slightly
    if (item.common && score > 0) {
      score += 10;
    }

    return { item, score };
  });

  // Filter and sort by score
  return scored
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(s => s.item);
}
